import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

const Root: React.FC = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          src="/assets/book1.jpg"
          height={144}
          width={144}
          alt="Book Image"
        />
      </main>

      <footer>Copyright ©2022 All rights reserved</footer>
    </>
  );
};

export default Root;
